version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "/etc/init.d/emol", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - EMOL_DEV=1
      - AWS_DEFAULT_REGION=ca-central-1
      - SSM_ENDPOINT_URL=http://localstack:4566
    volumes:
      - .:/opt/emol
      - static:/opt/emol/static
      - emol_logs:/var/log/emol
      - nginx_logs:/var/log/nginx
      - nginx_run:/run/nginx
    depends_on:
      - db
      - localstack
    networks:
      - emol-network

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=ssm
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ca-central-1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - emol-network

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=emol
      - MYSQL_USER=emol_db_user
      - MYSQL_PASSWORD=emol_db_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - emol-network

networks:
  emol-network:
    driver: bridge

volumes:
  mysql_data:
  static:
  emol_logs:
  nginx_logs:
  nginx_run:
