# !!! This is only used for development.
# In production we will load the container from the Dockerfile directly
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - DJANGO_SECRET_KEY=super_secret_key
      - DJANGO_SETTINGS_MODULE=emol.settings.dev_settings
      - EMOL_DEV=1
    volumes:
      - .:/mnt/emol
      - data:/mnt/data

volumes:
  data: