# !!! This is only used for development.
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - DJANGO_SECRET_KEY=super_secret_key
      - DJANGO_SETTINGS_MODULE=emol.settings.dev_settings
      - EMOL_DEV=1
      - DB_HOST=db
      - DB_NAME=emol
      - DB_USER=emol_db_user
      - DB_PASSWORD=emol_db_password
    volumes:
      - .:/mnt/emol
      - data:/mnt/data
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=emol
      - MYSQL_USER=emol_db_user
      - MYSQL_PASSWORD=emol_db_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  data:
  mysql_data: