# Generated by Django 4.1.7 on 2023-02-27 21:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cards.models.permissioned_db_fields
import cards.utility.crypto


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Authorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("card_issued", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Combatant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("card_id", models.CharField(max_length=255)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("accepted_privacy_policy", models.BooleanField(default=False)),
                (
                    "privacy_acceptance_code",
                    models.CharField(
                        default=cards.utility.crypto.get_random_32,
                        max_length=32,
                        null=True,
                        unique=True,
                    ),
                ),
                ("email", models.CharField(max_length=255, unique=True)),
                ("sca_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "legal_name",
                    cards.models.permissioned_db_fields.PermissionedCharField(
                        max_length=255
                    ),
                ),
                (
                    "phone",
                    cards.models.permissioned_db_fields.PermissionedCharField(
                        max_length=255
                    ),
                ),
                (
                    "address1",
                    cards.models.permissioned_db_fields.PermissionedCharField(
                        max_length=255
                    ),
                ),
                (
                    "address2",
                    cards.models.permissioned_db_fields.PermissionedCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "city",
                    cards.models.permissioned_db_fields.PermissionedCharField(
                        max_length=255
                    ),
                ),
                (
                    "province",
                    cards.models.permissioned_db_fields.PermissionedCharField(
                        default="ON", max_length=2
                    ),
                ),
                (
                    "postal_code",
                    cards.models.permissioned_db_fields.PermissionedCharField(
                        max_length=7
                    ),
                ),
                (
                    "dob",
                    cards.models.permissioned_db_fields.PermissionedDateField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "member_number",
                    cards.models.permissioned_db_fields.PermissionedIntegerField(
                        blank=True, null=True
                    ),
                ),
                (
                    "member_expiry",
                    cards.models.permissioned_db_fields.PermissionedDateField(
                        blank=True, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("is_global", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Waiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_signed", models.DateField()),
                (
                    "combatant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.combatant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.discipline",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissionas",
                        to="cards.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReminderEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_date", models.DateField()),
                ("is_expiration", models.BooleanField(default=False)),
                ("sent", models.BooleanField(default=False)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.card",
                    ),
                ),
                (
                    "waiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.waiver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("accepted", models.DateTimeField(blank=True, null=True)),
                (
                    "combatant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_acceptance",
                        to="cards.combatant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marshal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marshals",
                        to="cards.discipline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CombatantWarrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cards.card"
                    ),
                ),
                (
                    "marshal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cards.marshal",
                    ),
                ),
            ],
            options={
                "db_table": "cards_combatant_warrant",
            },
        ),
        migrations.CreateModel(
            name="CombatantAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "authorization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cards.authorization",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cards.card"
                    ),
                ),
            ],
            options={
                "db_table": "cards_combatant_authorization",
            },
        ),
        migrations.AddIndex(
            model_name="combatant",
            index=models.Index(fields=["uuid"], name="cards_comba_uuid_e4cbe6_idx"),
        ),
        migrations.AddIndex(
            model_name="combatant",
            index=models.Index(
                fields=["card_id"], name="cards_comba_card_id_b38110_idx"
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="authorizations",
            field=models.ManyToManyField(
                through="cards.CombatantAuthorization", to="cards.authorization"
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="combatant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="cards.combatant",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="discipline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cards.discipline"
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="warrants",
            field=models.ManyToManyField(
                through="cards.CombatantWarrant", to="cards.marshal"
            ),
        ),
        migrations.AddField(
            model_name="authorization",
            name="discipline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorizations",
                to="cards.discipline",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userpermission",
            unique_together={("user", "permission", "discipline")},
        ),
        migrations.AddIndex(
            model_name="privacyacceptance",
            index=models.Index(fields=["code"], name="cards_priva_code_d243f6_idx"),
        ),
        migrations.AddIndex(
            model_name="combatantwarrant",
            index=models.Index(fields=["uuid"], name="cards_comba_uuid_df78d5_idx"),
        ),
        migrations.AddIndex(
            model_name="combatantauthorization",
            index=models.Index(fields=["uuid"], name="cards_comba_uuid_732cb3_idx"),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(
                fields=("combatant", "discipline"), name="combatant_card"
            ),
        ),
    ]
