# Generated by Django 4.1.7 on 2023-03-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_alter_authorization_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorization",
            name="slug",
            field=models.SlugField(editable=False, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="authorization",
            unique_together={("slug", "discipline")},
        ),
    ]
