# Generated by Django 4.1.7 on 2023-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0004_reminder_remove_reminderemail_card_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
