# Generated by Django 4.1.7 on 2023-04-16 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0005_privacypolicy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privacypolicy",
            options={"verbose_name_plural": "Privacy policies"},
        ),
    ]
