# Generated by Django 4.1.7 on 2023-04-18 01:48

import uuid

import django.db.models.deletion
from django.db import migrations, models

import cards.utility.time


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0006_alter_privacypolicy_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=cards.utility.time.utc_tomorrow),
                ),
                (
                    "combatant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.combatant",
                    ),
                ),
            ],
        ),
    ]
