# Generated by Django 4.1.7 on 2023-04-20 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0007_updatecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updatecode",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
