# Generated by Django 4.2.11 on 2025-05-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0009_alter_combatant_province_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="region",
            name="cards_regio_code_17d4ab_idx",
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="region",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="region",
            name="postal_format",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="region",
            name="is_primary",
        ),
    ]
