# Generated by Django 4.2.11 on 2025-12-09 08:11

import uuid

import cards.utility.time
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0012_populate_regions"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "url_template",
                    models.CharField(
                        help_text="URL template with {code} placeholder, e.g., '/update/{code}/'",  # noqa: E501
                        max_length=500,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=cards.utility.time.utc_tomorrow),
                ),
                ("consumed", models.BooleanField(default=False)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "combatant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_codes",
                        to="cards.combatant",
                    ),
                ),
            ],
            options={
                "verbose_name": "One-Time Code",
                "verbose_name_plural": "One-Time Codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
