# Generated by Django 4.2.11 on 2025-12-09 08:18

from django.db import migrations


def add_pin_reset_permission(apps, schema_editor):
    """Add the can_initiate_pin_reset permission if it doesn't exist."""
    Permission = apps.get_model("cards", "Permission")
    if not Permission.objects.filter(slug="can_initiate_pin_reset").exists():
        Permission.objects.create(
            name="Can initiate PIN reset",
            slug="can_initiate_pin_reset",
            is_global=True,
            is_default=True,
        )


def remove_pin_reset_permission(apps, schema_editor):
    """Remove the can_initiate_pin_reset permission."""
    Permission = apps.get_model("cards", "Permission")
    Permission.objects.filter(slug="can_initiate_pin_reset").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_add_pin_fields'),
    ]

    operations = [
        migrations.RunPython(add_pin_reset_permission, remove_pin_reset_permission),
    ]
