# Generated by Django 4.2.11 on 2025-12-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_add_pin_reset_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatant',
            name='email',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
