# Generated by Django 4.2.11 on 2025-12-09 08:36

from urllib.parse import urljoin

from django.conf import settings
from django.db import migrations


def migrate_update_codes(apps, schema_editor):
    """Migrate existing UpdateCode records to OneTimeCode."""
    UpdateCode = apps.get_model("cards", "UpdateCode")
    OneTimeCode = apps.get_model("cards", "OneTimeCode")

    base_url = getattr(settings, "BASE_URL", "http://localhost:8000")

    for update_code in UpdateCode.objects.all():
        url_template = urljoin(base_url, f"/self-serve-update/{{{update_code.code}}}")
        url_template = url_template.replace(str(update_code.code), "{code}")

        OneTimeCode.objects.create(
            combatant=update_code.combatant,
            code=update_code.code,
            url_template=urljoin(base_url, "/self-serve-update/{code}"),
            expires_at=update_code.expires_at,
            consumed=False,
            consumed_at=None,
        )

    UpdateCode.objects.all().delete()


def reverse_migration(apps, schema_editor):
    """Reverse is a no-op since we can't restore deleted UpdateCodes."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_remove_email_unique'),
    ]

    operations = [
        migrations.RunPython(migrate_update_codes, reverse_migration),
    ]
