# Generated by Django 4.2.11 on 2025-12-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0017_migrate_update_codes_to_one_time_codes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UpdateCode",
        ),
    ]
