# Generated by Django 4.2.27 on 2026-01-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature_switches", "0002_add_granular_control"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureswitch",
            name="name",
            field=models.CharField(
                help_text="Unique identifier for this switch (e.g., 'pin_required')",
                max_length=100,
                unique=True,
            ),
        ),
    ]
