#!/bin/sh
### BEGIN INIT INFO
# Provides:          gunicorn
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Gunicorn at boot
# Description:       Enable Gunicorn service.
### END INIT INFO

ROOT=/opt/emol/emol
PID=/var/run/emol.pid
ENV_FILE=$ROOT/.env_dev

case "$1" in
  start)
    echo "Starting eMoL"
    cd $ROOT
    poetry run gunicorn \
        --pid $PID \
        --workers 3 \
        --bind unix:/opt/emol/emol.sock \
        --access-logfile - \
        --daemon \
        emol.wsgi:application
    ;;
  stop)
    echo "Stopping Gunicorn"
    kill -9 $(cat $PID)
    ;;
  status)
    if [ -f $PID ]; then
      echo "emol (gunicorn) is running with pid: $(cat $PID)"
    else
      echo "emol (gunicorn) is not running"
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/gunicorn {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
