#!/bin/sh
### BEGIN INIT INFO
# Provides:          gunicorn
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Gunicorn at boot
# Description:       Enable Gunicorn service.
### END INIT INFO

ROOT=/opt/emol/emol
PID=/var/run/emol.pid

case "$1" in
  start)
    echo "Starting eMoL"
    cd $ROOT
    poetry run gunicorn \
        --pid $PID \
        --workers 3 \
        --bind unix:/opt/emol/emol.sock \
        --access-logfile - \
        --daemon \
        emol.wsgi:application
    ;;
  stop)
    echo "Stopping Gunicorn"
    PID_TO_KILL=$(cat $PID)
    if [ -n "$PID_TO_KILL" ]; then
        kill -15 $PID_TO_KILL # Send SIGTERM first
        sleep 5 # Wait for graceful shutdown (adjust timeout as needed)
        if kill -0 $PID_TO_KILL 2>/dev/null; then # Check if process is still running
            kill -9 $PID_TO_KILL # Forcefully kill if still running
        fi
    fi
    ;;
  status)
    if [ -f $PID ]; then
      PID_STATUS=$(cat $PID)
      if kill -0 "$PID_STATUS" 2>/dev/null; then # Check if process is running
          echo "emol (gunicorn) is running with pid: $PID_STATUS"
      else
          echo "emol (gunicorn) is not running (PID file exists but process is not running)"
      fi
    else
      echo "emol (gunicorn) is not running (PID file not found)"
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/emol {start|stop|restart}"
    exit 1
    ;;
esac

exit 0